In [15]:
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.metrics import pairwise_distances

points1 = [[0, 0], [1,1], [100, 100]]
points2 = [[0.1, 0.1], [1000, 1000], [2,2], [1.1, 1.1]]

test_arr = pairwise_distances(points1, points2)

display(test_arr)
# кейс 1 - выбираем точки points2, которые ближе всего к точкам points2 0й, 1й и 2й соотв.
nearest_2_to_1 = test_arr.argmin(axis=1)
print(nearest_2_to_1)
# кейс 2 - точки, которые ближе порогового расстояния
closer_thresh_2_to_1 = np.where(test_arr < 250)[1]
print(closer_thresh_2_to_1)

to_select = nearest_2_to_1[pd.Series(nearest_2_to_1).isin( set(closer_thresh_2_to_1) )]

to_select
# argm = x_arr.argmin(axis=0)
# display(X.argmin(axis=1))

array([[1.41421356e-01, 1.41421356e+03, 2.82842712e+00, 1.55563492e+00],
       [1.27279221e+00, 1.41279935e+03, 1.41421356e+00, 1.41421356e-01],
       [1.41279935e+02, 1.27279221e+03, 1.38592929e+02, 1.39865721e+02]])

[0 3 2]
[0 2 3 0 2 3 0 2 3]


array([0, 3, 2])